### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ZackSoul** [markchen7788/doca_ar#1]
/opt/mellanox/iproute2/sbin/mlxdevm port function set pci/0000:03:00.0/229409 hw_addr 02:25:f2:8d:a2:4c trust on state active
/opt/mellanox/iproute2/sbin/mlxdevm port function set pci/0000:03:00.0/229410 hw_addr 02:25:f2:8d:a2:5c trust on state active
请问这个地方的hw_addr是pci的mac地址还是自己随意设置即可，因为本人刚开始接触这方面，所以麻烦您要是有空能回复一下我，这对刚入门的我很有帮助，谢谢您。

**Comment by markchen7788** [comment]
随意

**Comment by ZackSoul** [comment]
谢谢
